# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('last_price', models.IntegerField(default=0)),
                ('sector', models.CharField(max_length=128)),
                ('market_cap', models.IntegerField(default=0)),
            ],
        ),
    ]
